"""empty message

Revision ID: 19586a00c67c
Revises: b2701be5f74f
Create Date: 2020-05-27 14:14:47.379787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19586a00c67c'
down_revision = 'b2701be5f74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_pkey'),
    sa.UniqueConstraint('title', name='news_title_key')
    )
    # ### end Alembic commands ###
