"""empty message

Revision ID: 1ef6a1872a25
Revises: 2e7513310b94
Create Date: 2020-06-15 15:26:03.826792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef6a1872a25'
down_revision = '2e7513310b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'keywords')
    # ### end Alembic commands ###
