"""empty message

Revision ID: 2e7513310b94
Revises: ea8a67c6ad88
Create Date: 2020-06-01 16:44:07.067883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7513310b94'
down_revision = 'ea8a67c6ad88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('result', sa.JSON(), nullable=True))
    op.drop_column('news', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('news', 'result')
    # ### end Alembic commands ###
