"""empty message

Revision ID: 8ba15c1f2927
Revises: 4fdbc2f4a9a3
Create Date: 2020-05-26 11:07:26.574336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ba15c1f2927'
down_revision = '4fdbc2f4a9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('date', sa.String(), nullable=True))
    op.add_column('results', sa.Column('description', sa.String(), nullable=True))
    op.add_column('results', sa.Column('source', sa.String(), nullable=True))
    op.add_column('results', sa.Column('state', sa.String(), nullable=True))
    op.add_column('results', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('results', 'url')
    op.drop_column('results', 'result_no_stop_words')
    op.drop_column('results', 'result_all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('results', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('results', 'title')
    op.drop_column('results', 'state')
    op.drop_column('results', 'source')
    op.drop_column('results', 'description')
    op.drop_column('results', 'date')
    # ### end Alembic commands ###
