"""empty message

Revision ID: ea8a67c6ad88
Revises: 
Create Date: 2020-06-01 16:41:47.666336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8a67c6ad88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('county', sa.String(), nullable=True))
    op.drop_constraint('news_title_key', 'news', type_='unique')
    op.drop_column('news', 'title')
    op.drop_column('news', 'source')
    op.drop_column('news', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('news_title_key', 'news', ['title'])
    op.drop_column('news', 'county')
    # ### end Alembic commands ###
